apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: bootstrap-istiocontrolplane
spec:
  profile: minimal
  components:
    pilot:
      k8s:
        resources:
          requests:
            memory: 512Mi
